name: FastAPI OCR App

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'  # Run every 5 minutes

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run FastAPI application
      run: |
        uvicorn main:app --host 0.0.0.0 --port 3000 &
        echo $! > app.pid
        sleep 15  # Wait for app to start

    - name: Keep app running
      run: |
        while true; do
          if ! kill -0 $(cat app.pid) 2>/dev/null; then
            echo "App stopped unexpectedly"
            exit 1
          fi
          sleep 60  # Check every minute
        done &

  
