name: FastAPI OCR App

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'  # Run every 5 minutes

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run FastAPI application
      run: |
        uvicorn main:app --host 0.0.0.0 --port 3000 &
        echo $! > app.pid
        sleep 10  # Wait for app to start

    - name: Keep app running
      run: |
        while true; do
          if ! kill -0 $(cat app.pid) 2>/dev/null; then
            echo "App stopped unexpectedly"
            exit 1
          fi
          sleep 60  # Check every minute
        done &

    - name: Wait for manual stop
      run: |
        echo "App is running. Go to Actions -> This workflow -> Re-run jobs -> Click 'Cancel workflow' to stop the app."
        sleep 1800  # Run for 30 minutes max


        
